# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d35fbd63165fc28f783c93486f02eacdb3873f5f3f62ce0d13e8661c1c7646e7b32c8b988d5792a8a0662cf94e76272334049bc617f9c26115492a82a4aad57e

test:
  secret_key_base: 5654baf72392958122703084bda95828247000ce6b88fb4d00220a9168f7d722d7ce6481ebe5af90aed8ab544180dd8a6e402dba7773d27fd6ed70cddb0dc922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
